// oldcode/components/Todo.vue
<template>
  <div :title="reason" class="ma-3">
    <img src="https://thumbs.gfycat.com/QuaintTenderAmericanindianhorse-small.gif" alt="dancing arthur gif" height="75">
  </div>
</template>

<script>
export default {
  props: {
    reason: {
      type: String,
      default: null
    }
  }
};
</script>

// components/Todo.tsx
import React, { FC } from 'react';

interface TodoProps {
	reason?: string;
}

const Todo: FC<TodoProps> = (props) => {
	return (
		<div title={ props.reason }>
			<img src="https://thumbs.gfycat.com/QuaintTenderAmericanindianhorse-small.gif" alt="dancing arthur gif" height="75"/>
		</div>
	)
}

export default Todo;
